---
# K3s
k3s_version: "v1.36.0+k3s1"

# Cilium CNI
cilium_version: "1.19.3"

# CloudNativePG operator
cnpg_version: "0.28.2"

# cert-manager
certmanager_version: "v1.20.2"

# Cluster Autoscaler
autoscaler_server_type: "cpx32"
hetzner_location: "nbg1"

# SSH
ssh_port: 22022

# System user for deployments
deploy_user: deploy
